
! Event create string names (sEventCreateName)
- DOMMouseEvent: "mouseevent", "mouseevents" "mousescrollevents" "popupevents" 
- DOMKeyEvent:  "keyboardevent", "keyevents"
- DOMMutationEvent: "mutationevent", "mutationevents"  
- ??Event: "textevent", "textevents"  
- DOMPopupBlockedEvent: "popupblockedevents"
- DOMUIEvent: "uievent", "uievents"
- DOMEvent: "event", "events", "htmlevents"  
- DOMSVGEvent: "svgevent", "svgevents"  
- DOMSVGZoomEvent: "svgzoomevent", "svgzoomevents"  
- DOMXULCommandEvent: "xulcommandevent", "xulcommandevents"  
- DOMCommandEvent: "commandevent", "commandevents"  
- DOMDataContainerEvent: "datacontainerevent", "datacontainerevents"  
- DOMMessageEvent: "messageevent"
  
! Dom event names for use in initXXEvent() functions
"mousedown", "mouseup", "click", "dblclick", "mouseover",
"mouseout", "mousemove", "contextmenu", "keydown", "keyup", "keypress",
"focus", "blur", "load", "beforeunload", "unload", "abort", "error",
"submit", "reset", "change", "select", "input", "paint" ,"text",
"compositionstart", "compositionend", "popupshowing", "popupshown",
"popuphiding", "popuphidden", "close", "command", "broadcast", "commandupdate",
"dragenter", "dragover", "dragexit", "dragdrop", "draggesture",
"drag", "dragend", "resize",
"scroll", "overflow", "underflow", "overflowchanged",
"DOMSubtreeModified", "DOMNodeInserted", "DOMNodeRemoved", 
"DOMNodeRemovedFromDocument", "DOMNodeInsertedIntoDocument",
"DOMAttrModified", "DOMCharacterDataModified",
"DOMActivate", "DOMFocusIn", "DOMFocusOut",
"pageshow", "pagehide", "DOMMouseScroll", "offline", "online",
"copy", "cut", "paste"

