#ifndef __WX_MOZILLA_COMPONENTS_H
#define __WX_MOZILLA_COMPONENTS_H
/*
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Library General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */
 
/***************************************************************************
                          wxMozillaProtocolHandler.hpp
                             -------------------
    begin                : Jan 2003, 27
    copyright            : (C) 2002-2004 by David Teller
    email                : Yoric@users.sourceforge.net
    project              : OpenBERG (ported to wxMozilla by the author)
 ***************************************************************************/

/**
 * A unique idl identifier, as generated by uuidgen
 */
typedef struct
{
	wxUint32 m0 ;
	wxUint16 m1;
	wxUint16 m2;
	wxUint8   m3[8];
} wxUId;

#endif
