/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */



#ifndef PHP_MYSWIG_H
#define PHP_MYSWIG_H

extern zend_module_entry myswig_module_entry;
#define phpext_myswig_ptr &myswig_module_entry

#ifdef PHP_WIN32
# define PHP_MYSWIG_API __declspec(dllexport)
#else
# define PHP_MYSWIG_API
#endif

#ifdef ZTS
#include "TSRM.h"
#endif

PHP_MINIT_FUNCTION(myswig);
PHP_MSHUTDOWN_FUNCTION(myswig);
PHP_RINIT_FUNCTION(myswig);
PHP_RSHUTDOWN_FUNCTION(myswig);
PHP_MINFO_FUNCTION(myswig);

ZEND_NAMED_FUNCTION(_wrap_Swig_variable_set);
ZEND_NAMED_FUNCTION(_wrap_Swig_variable_get);
ZEND_NAMED_FUNCTION(_wrap_Swig_fact);
ZEND_NAMED_FUNCTION(_wrap_Swig_div);
#endif /* PHP_MYSWIG_H */
