/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */



#ifndef PHP_MYCLASS_H
#define PHP_MYCLASS_H

extern zend_module_entry myclass_module_entry;
#define phpext_myclass_ptr &myclass_module_entry

#ifdef PHP_WIN32
# define PHP_MYCLASS_API __declspec(dllexport)
#else
# define PHP_MYCLASS_API
#endif

#ifdef ZTS
#include "TSRM.h"
#endif

PHP_MINIT_FUNCTION(myclass);
PHP_MSHUTDOWN_FUNCTION(myclass);
PHP_RINIT_FUNCTION(myclass);
PHP_RSHUTDOWN_FUNCTION(myclass);
PHP_MINFO_FUNCTION(myclass);

ZEND_NAMED_FUNCTION(_wrap_Vector_x_set);
ZEND_NAMED_FUNCTION(_wrap_Vector_x_get);
ZEND_NAMED_FUNCTION(_wrap_Vector_y_set);
ZEND_NAMED_FUNCTION(_wrap_Vector_y_get);
ZEND_NAMED_FUNCTION(_wrap_Vector_z_set);
ZEND_NAMED_FUNCTION(_wrap_Vector_z_get);
ZEND_NAMED_FUNCTION(_wrap_new_Vector);
ZEND_NAMED_FUNCTION(_wrap_Vector_magnitude2);
ZEND_NAMED_FUNCTION(_wrap_callCallback);
ZEND_NAMED_FUNCTION(_wrap_callMemberCallback);
#endif /* PHP_MYCLASS_H */
