// A bunch of %rename directives generated by BuildRenamers in config.py
// in order to remove the wx prefix from all global scope names.

#ifndef BUILDING_RENAMERS

%rename(MOZ_MAJOR_VERSION)                  wxMOZ_MAJOR_VERSION;
%rename(MOZ_MINOR_VERSION)                  wxMOZ_MINOR_VERSION;
%rename(MOZ_RELEASE_NUMBER)                 wxMOZ_RELEASE_NUMBER;
%rename(MozillaBrowser)                     wxMozillaBrowser;
%rename(MozillaWindow)                      wxMozillaWindow;
%rename(MozillaSettings)                    wxMozillaSettings;
%rename(MOZILLA_STATE_START)                wxMOZILLA_STATE_START;
%rename(MOZILLA_STATE_NEGOTIATING)          wxMOZILLA_STATE_NEGOTIATING;
%rename(MOZILLA_STATE_REDIRECTING)          wxMOZILLA_STATE_REDIRECTING;
%rename(MOZILLA_STATE_TRANSFERRING)         wxMOZILLA_STATE_TRANSFERRING;
%rename(MOZILLA_STATE_STOP)                 wxMOZILLA_STATE_STOP;
%rename(MOZILLA_STATE_IS_REQUEST)           wxMOZILLA_STATE_IS_REQUEST;
%rename(MOZILLA_STATE_IS_DOCUMENT)          wxMOZILLA_STATE_IS_DOCUMENT;
%rename(MOZILLA_STATE_IS_NETWORK)           wxMOZILLA_STATE_IS_NETWORK;
%rename(MOZILLA_STATE_IS_WINDOW)            wxMOZILLA_STATE_IS_WINDOW;
%rename(MOZILLA_IS_INSECURE)                wxMOZILLA_IS_INSECURE;
%rename(MOZILLA_IS_BROKEN)                  wxMOZILLA_IS_BROKEN;
%rename(MOZILLA_IS_SECURE)                  wxMOZILLA_IS_SECURE;
%rename(MOZILLA_SECURE_HIGH)                wxMOZILLA_SECURE_HIGH;
%rename(MOZILLA_SECURE_MED)                 wxMOZILLA_SECURE_MED;
%rename(MOZILLA_SECURE_LOW)                 wxMOZILLA_SECURE_LOW;
%rename(MOZILLA_CONTEXT_DOCUMENT)           wxMOZILLA_CONTEXT_DOCUMENT;
%rename(MOZILLA_CONTEXT_LINK)               wxMOZILLA_CONTEXT_LINK;
%rename(MOZILLA_CONTEXT_TEXT)               wxMOZILLA_CONTEXT_TEXT;
%rename(MOZILLA_CONTEXT_BACKGROUND_IMAGE)   wxMOZILLA_CONTEXT_BACKGROUND_IMAGE;
%rename(MOZILLA_CONTEXT_IMAGE)              wxMOZILLA_CONTEXT_IMAGE;
%rename(MozillaBeforeLoadEvent)             wxMozillaBeforeLoadEvent;
%rename(MozillaLinkChangedEvent)            wxMozillaLinkChangedEvent;
%rename(MozillaStateChangedEvent)           wxMozillaStateChangedEvent;
%rename(MozillaSecurityChangedEvent)        wxMozillaSecurityChangedEvent;
%rename(MozillaLoadCompleteEvent)           wxMozillaLoadCompleteEvent;
%rename(MozillaStatusChangedEvent)          wxMozillaStatusChangedEvent;
%rename(MozillaTitleChangedEvent)           wxMozillaTitleChangedEvent;
%rename(MozillaProgressEvent)               wxMozillaProgressEvent;
%rename(MozillaRightClickEvent)             wxMozillaRightClickEvent;

#endif
