name: netscavator # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '6.5.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: Webscraper robot and IDE for large scale automated scraping # 79 char long summary
description: |
  IDE and robot for easy automated webscraping. System can scrape using
  simple plain HTML (Beautiful soup style) and full browser like Selenium.
  DOM sequence approach ensures very robust scripts.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: classic # use 'strict' once you have the right plugs and slots

apps:
  netscavator:
    command: usr/bin/netscavator
  netcreator:
    command: usr/bin/netcreator

build-packages:
  - nano
  - less
  - cmake
  - python3-pip
  - libbz2-dev
  - qt6-base-dev
  - qt6-base-dev-tools
  - qt6-webengine-dev
  - qt6-webengine-dev-tools
  - qt6-quick3d-dev
  - qt6-quick3d-dev-tools
  - qt6-declarative-dev
  - libqt6opengl6-dev
  - libqt6webenginewidgets6
  - libqt6widgets6
  - libboost-all-dev
  - libssl-dev
  - libcurl4-openssl-dev
  - pkg-config
  - libavcodec-dev
  - libavdevice-dev
  - libavdevice58
  - libavfilter-dev
  - libavformat-dev
  - libavutil-dev
  - libdlna-dev
  - libffmpeg-nvenc-dev
  - libffmpeg-ocaml-dev
  - libffmpegthumbnailer-dev
  - libpostproc-dev
  - libsdl-kitchensink-dev
  - libswresample-dev
  - libswscale-dev
  - mkchromecast
  - libsdl2-dev
  - libsdl2-gfx-dev
  - libsdl2-image-dev
  - libsdl2-mixer-dev
  - libsdl2-net-dev
  - libsdl2-ttf-dev
  - libsndifsdl2-dev


parts:
  install-needed:
    plugin: nil
    override-pull: |
      pip install conan


  netscavator-main:
    source: https://github.com/mlutken/netscavator.git
    override-pull: |
        echo "Touch pullstep 8"
        if [ ! -d netscavator ]; then
            git clone https://github.com/mlutken/netscavator.git;
        fi
        pushd netscavator
        pwd
        exit 0;
        if [ ! -d cpaf ]; then
            git clone https://github.com/mlutken/cpaf.git;
        fi

        git pull
        git submodule init
        git submodule update --recursive
        popd

    override-build: |
        echo "Touch buildstep 7"
        pwd
        cd ~/parts/netscavator-main/src
        pushd netscavator
        ./snapcraft-build.sh
        #./code/3rdpartysrc/build_3rdparty_release.sh
        #popd
        #pushd netscavator
        #./cpaf/build_3rdparty_cpaf.sh
        #popd
        #pushd netscavator
        #./build.sh -b=release --test=n
        popd

    override-stage: |
        echo "Touch stage step 3"
        pwd
        cd ~/parts/netscavator-main/src
        pushd netscavator
        ./snapcraft-stage.sh
        popd

    override-prime: |
        pwd
        cp -r ~/stage/* ~/prime

    plugin: dump
    after:
      - install-needed

